[build]
  # This is a static site, so we publish directly from the root directory
  publish = "."
  
  # Explicitly set an empty build command as this is a static site
  command = "echo 'Static site - no build step required'"

[[redirects]]
  # Single-page app fallback
  from = "/*"
  to = "/index.html"
  status = 200 